name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: ["opened", "reopened", "edited", "synchronize"]
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
env:
  CARGO_TERM_COLOR: always
jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy
      - uses: swatinem/rust-cache@v2
        with:
          workspaces: "./target -> target"
      - uses: taiki-e/install-action@nextest
      - name: Check formatting
        run: cargo +nightly fmt --check
      - name: Lint
        run: cargo clippy --locked -- -D warnings
      - name: Test
        run: cargo nextest run --locked
